spring:
  application:
    name: gateway
    
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=BamxDev;encrypt=false;trustServerCertificate=false;integratedSecurity=false;
    username: sa
    password: Paisano1248.
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari: 
      connection-test-query: select 1
  jpa:
    show-sql: true
    